name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: >-
        A clear and concise description of the bug.
    validations:
      required: true
  - type: dropdown
    id: client
    attributes:
      label: Channel
      multiple: false
      description: Which Edge channel do you use?
      options:
        - Stable (default)
        - Beta
        - Dev
        - Canary
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Search Engine
      multiple: false
      description: Which search engine do you use?
      options:
        - Google
        - Bing
        - DuckDuckGo
        - Yahoo
        - Yandex
        - Ecosia
        - Ask
        - Qwant
        - Perplexity
        - Others
    validations:
      required: true
  - type: textarea
    id: custom-search-engine
    attributes:
      label: If you selected “Others”, what is the request URL?
      description: >-
        You can find it in the registry under "HKEY_LOCAL_MACHINE\SOFTWARE\valnoxy\GoAwayEdge\CustomQueryUrl".
    validations:
      required: false
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce
      description: >-
        Minimal and precise steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        Please attach the installation log using the field below. The log file is located under “C:\Users\Username\AppData\Local\Temp\GoAwayEdge\Logs”.

        You may also include any additional information, screenshots, or files that helpful in describing the issue.
